spring:
  application:
    name: twitterd

logging:
  level:
    io.lw900925: debug

app:
  base-url: https://api.twitter.com/1.1
  proxy:
    host: 127.0.0.1
    port: 7890
  access-token:
  count: 200
  increment: true
  users-file-path: ${user.dir}/config/users.txt
  media-download-path: ${user.dir}/downloads
