spring:
  application:
    name: twid

logging:
  level:
    io.lw900925.twid: debug

twi:
  twitter:
    api:
      base-url: https://api.twitter.com/1.1
      access-token:
    proxy:
      host: 127.0.0.1
      port: 7890
  list: ${user.dir}/config/list.txt
  cache: ${user.dir}/cache/timeline_id.json
  location: ${user.dir}/downloads
